### ISSUE TITLE
How to use image as watermark on Refile Image

### ISSUE THREAD

**Issue by samsoft00** [zyphlar/refile-watermark#1]
The title say it all, i want my website logo to be on every Refile Image, please how can that be achieve? Thanks

**Comment by zyphlar** [comment]
You'll have to use `:fill_watermark_image` but you'll probably have to edit the code because I'm not sure if the Gravity option adequately positions things. Maybe you'll have to write some more code to accept x/y position arguments or use the "gravity" option to automatically place the watermark as desired.

This isn't an issue with the code though and I'm not a free Refile consultant, so I'm closing this issue. Maybe ask StackOverflow or IRC or Upwork if you need further help.
